### PR TITLE
#158755843 Ratings And Reviews

### PR DESCRIPTION
**Pull request by clintfidel**
#### What does this PR do?
This PR allows allows users review and rate a particular product in the store
#### Description of Task to be completed?
- add model for storing users reviews and ratins
- create plugin for reviews and rates
- add forms to add reviews and rates
#### How should this be manually tested?
- pull the branch
- type reaction to start the app
- sign in as a user, select a product
- At the rare right enter a review and then rate also
- Click on Add Review burron
#### Screenshots (if appropriate)
screen shot 2018-07-19 at 3 59 50 pm

screen shot 2018-07-19 at 1 19 58 pm

#### What are the relevant pivotal tracker stories?
[Finishes #158755843](https://www.pivotaltracker.com/story/show/158755843)

#### Any background context you want to provide?
N/A

### CODE REVIEW

**Comment by Daramola98** [comment]
Good Job @clintfidel LGTM woop woop   🔥🔥🔥

**Comment by abdulfataiaka** [comment]
@clintfidel, if you check the plugin folders in the `/imports/plugins/core` and `/imports/plugins/included` directories, you will notice that the plugin folder names are not `camel` nor `pascal` cased, kindly use the appropriate form for your plugin folder name.

**Comment by abdulfataiaka** [comment]
@clintfidel, why do we have the `package-lock.json` as part of your changes? kindly remove it, thanks.

**Comment by abdulfataiaka** [comment]
@clintfidel, your branch name does not follow convection, please look into that, thanks.

**Comment by abdulfataiaka** [comment]
@clintfidel 

- The scope of your commit message should be `pascal` cased and not `spaced`
- The commit message title should very short, precise and descriptive
- The commit message body should hold the listing of what have been done to implement the feature

Please checkout the link below
https://github.com/andela/asgard-rc/wiki/Git-naming-conventions-and-best-practices

**Comment by ddouglasz** [comment]
LGTM. Personally had a one on one with you to go through the code base. Good job bro.

**Comment by abdulfataiaka** [comment]
@ddouglasz, what do you think of my comments?

**Comment by Rhotimee** [comment]
Nice work man. 
Implement the observations pointed out by @abdulfataiaka.
Otherwise, LGTM.

**Pull request closed without merging**
