### PR TITLE
#158963377 Update Readme file content

### PR DESCRIPTION
**Pull request by abdulfataiaka**
#### What does this PR do?
Update the Readme file to describe specifically how the application should be setup locally and remove unused top badges

#### Description of Task to be completed?
- Clean up the top badges
- Update getting started section for setting up application locally

#### How should this be manually tested?
- Visit `asgard-rc` repository at https://github.com/andela/asgard-rc

#### Any background context you want to provide?
Currently, the Readme content describe how to setup the latest version of reaction locally and not the specific one we are working on, hence this needs to be updated to reflect the way this specific one should be setup locally.

#### What are the relevant pivotal tracker stories?
[#158870586](https://www.pivotaltracker.com/story/show/158870586)

#### Screenshots (if appropriate)
None

### CODE REVIEW

**Comment by Daramola98** [comment]
LGTM

**Review by clintfidel — APPROVED** [review]
LGTM

**Comment by Rhotimee** [comment]
LGTM

**Comment by ddouglasz** [comment]
LGTM

**Comment by ddouglasz** [comment]
LGTM

**Comment by saheedt** [comment]
Looks good. We can merge this.

**Comment by OlatunjiYso** [comment]
LGTM

**Pull request merged**
