### PR TITLE
#159297524 Upload digital products

### PR DESCRIPTION
**Pull request by saheedt**
#### What does this PR do?
- This PR provides an interface to upload and sell digital products
#### Description of Task to be completed?
- Create option for selecting type of product getting added
- Create field for digital product upload
#### How should this be manually tested?
- Create a product using a vendor or admin account.
#### Any background context you want to provide?
- N/A
#### What are the relevant pivotal tracker stories?
- [#159297524](https://www.pivotaltracker.com/story/show/159297524)
#### Screenshots (if appropriate)
screen shot 2018-07-26 at 11 01 24 am

### CODE REVIEW

**Comment by Daramola98** [comment]
@saheedt Please can we have a proper description of the task to be completed in your PR

**Comment by saheedt** [comment]
@Daramola98  rectified..

**Comment by Daramola98** [comment]
Good Job @saheedt LGTM

**Comment by OlatunjiYso** [comment]
@saheedt , good job.
The scope of your commit message should have been in camel case and not hyphenated.
I.e `(upload-digital-products)` should have been `(uploadDigitalProducts)`

**Comment by OlatunjiYso** [comment]
@saheedt ,
can you have your story id point to the pivotal tracker ?
such that it would be clickable to reveal the story.
`[Story Id comes here ]( url comes here )` and it would become a link.

**Comment by saheedt** [comment]
@OlatunjiYso I have corrected all there is to correct. Please review and recommend for merge if it's satisfactory

**Comment by Rhotimee** [comment]
Makes sense.. LGTM

**Comment by ddouglasz** [comment]
Oh great, LGTM. I would nicely just learn from the story id link recommended by @olatunji to correct mine now.

**Comment by OlatunjiYso** [comment]
LGTM. Nice job @saheedt

**Comment by saheedt** [comment]
Hi @abdulfataiaka please look into this and kindly merge if it's good to go. thanks

**Pull request merged**
