### PR TITLE
Chore integrate circleci badge #158870539

### PR DESCRIPTION
**Pull request by ddouglasz**
**What does this PR do?**
Update the Readme file with Circle CI badge and integrate circle CI with the project.

**Description of Task to be completed?**
   - Clean up the top badges

**How should this be manually tested?**
   - Visit `asgard-rc` repository at https://github.com/andela/asgard-rc/tree/chore-integrate-circleci- 
      badge-%23158870539

**Any background context you want to provide?**
   - CircleCI acts as a platform for both Continuous Integration and Continuous Deployment. It tests all 
      changes that you are making to your codes.

**What are the relevant pivotal tracker stories?**
 -  #158870539

**Screenshots (if appropriate)**

None

### CODE REVIEW

**Comment by Rhotimee** [comment]
Hey Douglas, I can see multiple commits, I think we should just have only one commit for a branch.  Apart from that, LGTM.

**Comment by ddouglasz** [comment]
Hi Rotimi, there is an option to squash and merge( the other commits will be combined into one commit in the base branch as can be seen on the `squash and merge` button).

**Comment by Daramola98** [comment]
LGTM

**Comment by saheedt** [comment]
This looks good for merging.

**Comment by clintfidel** [comment]
@ddouglasz This looks good to me, however, I think you should squash all commits from your end.

**Comment by OlatunjiYso** [comment]
LGTM

**Comment by abdulfataiaka** [comment]
@ddouglasz, please ensure you always have one commit on your PR, try to squash these commits into one, thanks.

**Comment by abdulfataiaka** [comment]
@ddouglasz, Your PR description headings doesn't follow the stated convections, please use the appropriate `markdowns`

**Comment by ddouglasz** [comment]
Okay, @abdulfataiaka I would work on it now. Thank you.

**Comment by saheedt** [comment]
@ddouglasz  you can look at the wiki here 👉🏽https://github.com/andela/asgard-rc/wiki/Git-naming-conventions-and-best-practices  for the the PR description

**Comment by ddouglasz** [comment]
Thanks, @saheedt. Going there now!😎

**Pull request merged**
