### PR TITLE
#158870733 Add Codeclimate To Project Repo For Code Quality And Styling 

### PR DESCRIPTION
**Pull request by clintfidel**
#### What does this PR do?
Add code climate to project repo for code quality and styling

#### Description of Task to be completed?
- Add code climate badges to readme file

#### How should this be manually tested?
- Visit `asgard-rc` repository at https://github.com/andela/asgard-rc/tree/chore-integrate-codeclimate-158870733

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#158870733](https://www.pivotaltracker.com/story/show/158870733)

#### Screenshots (if appropriate)
None

### CODE REVIEW

**Comment by abdulfataiaka** [comment]
LGTM

**Comment by Daramola98** [comment]
LGTM

**Comment by Rhotimee** [comment]
LGTM

**Comment by saheedt** [comment]
There are conflicts, please resolve..

**Comment by saheedt** [comment]
The conflicts are gone but the badges don't show up on readme, based on the test link posted on the PR.

**Comment by saheedt** [comment]
The test seems to be failing now.. @clintfidel please attend to this so we can move forward with merging

**Pull request merged**
