### PR TITLE
#158755844 Vendors should be effectively onboarded to the app

### PR DESCRIPTION
**Pull request by Daramola98**
#### What does this PR do?
- Implements Vendors should be effectively onboard to the application 

#### Description of Task to be completed?
- Integrate Intro.js to give tour to vendors when they click the take a tour button

#### How should this be manually tested?
- Setup the application with the information on the readme
- Login as an admin or vendor and the click the take a tour button on the navbar you would be taken on a brief tour of the application

#### Any background context you want to provide?
- N/A

#### What are the relevant pivotal tracker stories?
- #158755844

#### Screenshots (if appropriate)
screen shot 2018-07-17 at 6 01 32 pm

### CODE REVIEW

**Comment by Rhotimee** [comment]
LGTM ✔️

**Comment by abdulfataiaka** [comment]
@Rhotimee, How did it behave locally on your end?

**Comment by abdulfataiaka** [comment]
@Daramola98, Please checkout the commit message convection on how wiki page and update as necessary 🙇

**Comment by ddouglasz** [comment]
LGTM.

**Comment by abdulfataiaka** [comment]
@ddouglasz, What do you think about @Daramola98's commit message?

**Comment by abdulfataiaka** [comment]
Also @ddouglasz, did you test this feature locally?

**Comment by ddouglasz** [comment]
@abdulfataiaka I was able to test his feature locally and it worked just fine.
@Daramola98 tried running the already existing tests on the project but it failed locally, same with me too. rebuilding Circle-CI remotely actually passed his feature. I guess that should work for now.

**Comment by abdulfataiaka** [comment]
@Daramola98, does it still fail locally and why?

**Comment by Daramola98** [comment]
So it seems the cart documents on the database is empty and it is expecting to find some documents in there

**Comment by abdulfataiaka** [comment]
Ok, please continue to look into it aside to ensure it passes, secondly @Daramola98, Is the `admin` suppose to get the same tour as `vendor`, in fact, is `admin` suppose to even suppose to get a `take a tour` button at all?

**Comment by saheedt** [comment]
I think we need to get tests passing both locally and remotely before we proceed.

**Comment by Daramola98** [comment]
Since it is not a forced tour I think it is ok for the button to appear for admins also. As they would have to click on the button to take the tour

**Comment by abdulfataiaka** [comment]
@Daramola98, what we are looking at is whats necessary to be seen and where for users, this is about `UX`. The `Take a Tour` button is for vendors, and to see this by admin feels weird.

**Comment by abdulfataiaka** [comment]
@Daramola98, lets ensure the `admin` doesn't see the button, as if its going to be seen by the `admin`, then it should show `admin` specific things during the tour and not the `vendor`'s

**Comment by Daramola98** [comment]
Will work on this @abdulfataiaka

**Comment by Rhotimee** [comment]
@abdulfataiaka @Daramola98, The tests are are passing and the feature is working fine. 
I think @abdulfataiaka is right. The admin is not supposed to see the take a tour button. 
Great job Dara.  👍🏾

**Review by clintfidel — COMMENTED** [review]
@Daramola98 , great job, but just like some other comments pointed out, I don't think an admin should see take a tour button aside that LGTM. Good job

**Comment by OlatunjiYso** [comment]
LGTM. Good job

**Comment by abdulfataiaka** [comment]
LGTM

**Comment by saheedt** [comment]
It all passes now.. So we are good to go on this..

**Comment by abdulfataiaka** [comment]
put your own LGTM 😠

**Pull request merged**
