### PR TITLE
#158755846 Paystack Integration

### PR DESCRIPTION
**Pull request by saheedt**
#### What does this PR do?
This PR allows users pay with Paystack during product checkout
#### Description of Task to be completed?
- Create a settings screen for adding Paystack public and secret key
- Create a checkout form
- Redirect to summary page when payment succeeds
#### How should this be manually tested?
- pull the branch
- type reaction in the CLI to start the app
- sign in as a Admin
- Input Paystack test keys
- Buy and checkout product 
#### Any background context you want to provide?
- N/A
#### What are the relevant pivotal tracker stories?
- #158755846
#### Screenshots (if appropriate)
screen shot 2018-07-23 at 7 28 02 am
screen shot 2018-07-23 at 7 12 57 am
screen shot 2018-07-23 at 7 13 20 am

### CODE REVIEW

**Comment by Daramola98** [comment]
@saheedt Please use the PR template found in the project wiki to correct the title of your PR and also tend to the circle ci issues. Gracias

**Comment by Daramola98** [comment]
Btw you forgot to remove the dd file @saheedt

**Comment by abdulfataiaka** [comment]
@saheedt, please follow convection with your PR title.

**Comment by saheedt** [comment]
@abdulfataiaka , sorry about the oversight, I just edited the PR title

**Pull request merged**
