### PR TITLE
#158755849 Static pages management

### PR DESCRIPTION
**Pull request by OlatunjiYso**
#### What does this PR do?
This PR allows the admin to manage static pages and users view static pages
#### Description of Task to be completed?
- add model for storing static pages in database
- create plugin for static pages
- add templates for viewing static page (users)
- add templates for static page management (admin)
- add components and containers for static pages
- add forms to add and edit static page
- add table for managing static pages
#### How should this be manually tested?
- pull the branch
- run `reaction reset -n`
- reaction to start the app
- signin as admin and find the plus icon on the admin side-nav
- select it and add and manage pages
#### Screenshots (if appropriate)
screen shot 2018-07-19 at 12 28 41 pm
screen shot 2018-07-19 at 12 24 49 pm
screen shot 2018-07-19 at 12 27 17 pm
screen shot 2018-07-19 at 12 26 47 pm

#### What are the relevant pivotal tracker stories?
[Finishes #158755849](https://www.pivotaltracker.com/n/projects/2182264)

#### Any background context you want to provide?
N/A

### CODE REVIEW

**Comment by abdulfataiaka** [comment]
@OlatunjiYso, this is what I see when I tried it out 👇 

screen shot 2018-07-19 at 2 38 42 pm
screen shot 2018-07-19 at 2 39 14 pm

Here is the link to the PR review app 👇 
https://asgard-rc-staging-pr-9.herokuapp.com/

**Comment by OlatunjiYso** [comment]
@abdulfataiaka ,
That is because you have not added a page yet.

**Comment by OlatunjiYso** [comment]
@abdulfataiaka ,  
On the admin panel, there is a "plus" icon on the side-toolbar that allows you add pages.

**Comment by abdulfataiaka** [comment]
@OlatunjiYso, is it possible to have the content of the dropdown say `you haven't added any page yet` or something similar when there are no added pages?  as this improves user experience as opposed to user thinking its a bug.

**Comment by OlatunjiYso** [comment]
@abdulfataiaka , the issue of having an empty dropdown if the admin has not added a page yet has been fixed.
If no pages are present yet, and the drop down is clicked, `no pages added yet ` would be displayed, and if `no pages added yet ` is clicked, it leads no where.

**Pull request merged**
